services:
  app:
    image: sofyanabdullah/devops-app
    container_name: devops-app
    ports:
      - "9000:8080"
    volumes:
      - ./app:/app
    environment:
      MONGODB_URL: mongodb://jenkins_mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: jenkins_mongo
    volumes:
      - mongo_data:/data/db

volumes:
  - /tmp/devops_app:/app
